development:
  adapter: postgresql
  database: magic_eight_ball_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: magic_eight_ball_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: magic_eight_ball_production
  pool: 5
  timeout: 5000
